import React, { useState } from 'react';
import { Link } from 'react-router-dom';
import { useForm } from 'react-hook-form';
import { Mail, ArrowRight, ShieldAlert, Sparkles, CheckCircle2 } from 'lucide-react';
import axios from 'axios';

export const ForgotPassword: React.FC = () => {
  const [successMsg, setSuccessMsg] = useState<string | null>(null);
  const [errorMsg, setErrorMsg] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const [resetLinkToken, setResetLinkToken] = useState<string | null>(null);

  const { register, handleSubmit, formState: { errors } } = useForm();
  
  const API_URL = import.meta.env.VITE_API_URL || 'http://localhost:5000/api';

  const onSubmit = async (data: any) => {
    setLoading(true);
    setErrorMsg(null);
    setSuccessMsg(null);
    try {
      const res = await axios.post(`${API_URL}/auth/forgot-password`, data);
      setSuccessMsg(res.data.message);
      // For demonstration convenience, we display the generated mock token so the user can easily proceed.
      if (res.data.resetToken) {
        setResetLinkToken(res.data.resetToken);
      }
    } catch (err: any) {
      console.error(err);
      setErrorMsg(err.response?.data?.message || 'Failed to submit request.');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-[85vh] flex items-center justify-center px-4 py-12 relative overflow-hidden">
      <div className="absolute top-1/4 left-1/2 -translate-x-1/2 -translate-y-1/2 w-96 h-96 bg-amber-500/10 rounded-full blur-[100px] pointer-events-none" />

      <div className="w-full max-w-md glass-premium rounded-3xl p-8 border border-slate-800 animate-fadeIn relative">
        <div className="flex justify-center mb-6">
          <div className="bg-amber-500/10 p-3.5 rounded-2xl border border-amber-500/20 text-amber-500">
            <Sparkles size={24} />
          </div>
        </div>

        <h2 className="text-2xl font-bold text-center text-slate-100 tracking-tight">Recover Password</h2>
        <p className="text-center text-slate-400 text-xs mt-1 mb-8">Enter your registered email to request a reset link</p>

        {errorMsg && (
          <div className="mb-6 bg-red-500/10 border border-red-500/20 rounded-xl p-3.5 flex items-start gap-3">
            <ShieldAlert size={18} className="text-red-400 shrink-0 mt-0.5" />
            <span className="text-xs text-red-300 leading-normal">{errorMsg}</span>
          </div>
        )}

        {successMsg ? (
          <div className="space-y-6 text-center">
            <div className="bg-emerald-500/10 border border-emerald-500/20 rounded-2xl p-5 flex flex-col items-center gap-3">
              <CheckCircle2 size={36} className="text-emerald-400" />
              <p className="text-sm text-emerald-300 font-semibold">{successMsg}</p>
              <p className="text-xs text-slate-400 mt-2">Check your inbox for a mock reset link. For testing/demo, click the button below to navigate directly using the mock token generated by the server.</p>
            </div>

            {resetLinkToken && (
              <Link
                to={`/reset-password?token=${resetLinkToken}`}
                className="w-full bg-emerald-500 hover:bg-emerald-600 text-slate-950 font-bold py-2.5 rounded-xl transition-all flex items-center justify-center gap-2 shadow-lg shadow-emerald-500/15 text-xs"
              >
                Go to Reset Password Screen <ArrowRight size={14} />
              </Link>
            )}

            <p className="text-xs text-slate-500">
              <Link to="/login" className="text-amber-500 hover:underline">Back to Login</Link>
            </p>
          </div>
        ) : (
          <form onSubmit={handleSubmit(onSubmit)} className="space-y-5">
            <div className="space-y-1.5">
              <label className="text-xs text-slate-400 font-medium">Campus Email Address</label>
              <div className="relative">
                <Mail size={16} className="absolute left-3.5 top-1/2 -translate-y-1/2 text-slate-500" />
                <input
                  type="email"
                  placeholder="you@college.edu"
                  className="w-full bg-slate-950/50 border border-slate-800 focus:border-amber-500 rounded-xl py-2.5 pl-10 pr-4 text-sm text-slate-200 focus:outline-none transition-colors"
                  {...register('email', { required: 'Email address is required' })}
                />
              </div>
              {errors.email && <span className="text-[10px] text-red-400 font-medium">{errors.email.message as string}</span>}
            </div>

            <button
              type="submit"
              disabled={loading}
              className="w-full bg-amber-500 hover:bg-amber-600 active:scale-[0.98] text-slate-950 font-bold py-2.5 rounded-xl transition-all flex items-center justify-center gap-2 shadow-lg shadow-amber-500/10 text-sm mt-8 disabled:opacity-50"
            >
              {loading ? 'Submitting request...' : 'Send Reset Link'}
              {!loading && <ArrowRight size={16} />}
            </button>

            <p className="text-center text-xs text-slate-400 mt-6">
              Remembered your password?{' '}
              <Link to="/login" className="text-amber-500 font-semibold hover:underline">Log In</Link>
            </p>
          </form>
        )}
      </div>
    </div>
  );
};
